name: Release

on:
  push:
    tags:
      - 'v*' # Воркфлоу запустится только при пуше тегов, начинающихся с "v" (например, v1.0.0)

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Необходимо для создания релиза на GitHub

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Загружаем всю историю git, чтобы сработал git describe в Makefile

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Run Tests
        run: make test

      - name: Build All Platforms
        run: make build-all

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            logspector-linux
            logspector.exe
            logspector-macos
          generate_release_notes: true